
-- 1. ROLE_T 삽입
INSERT INTO ROLE_T (ROLE_ID, ROLE_NAME) VALUES (SQ_ROLE_ID.NEXTVAL, 'PM');
INSERT INTO ROLE_T (ROLE_ID, ROLE_NAME) VALUES (SQ_ROLE_ID.NEXTVAL, 'PL');
INSERT INTO ROLE_T (ROLE_ID, ROLE_NAME) VALUES (SQ_ROLE_ID.NEXTVAL, '분석자');
INSERT INTO ROLE_T (ROLE_ID, ROLE_NAME) VALUES (SQ_ROLE_ID.NEXTVAL, '설계자');
INSERT INTO ROLE_T (ROLE_ID, ROLE_NAME) VALUES (SQ_ROLE_ID.NEXTVAL, '프로그래머');
INSERT INTO ROLE_T (ROLE_ID, ROLE_NAME) VALUES (SQ_ROLE_ID.NEXTVAL, '테스터');

-- 2. SKILL 삽입
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'JAVA');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'PYTHON');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'C++');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'ORACLE');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'ORACLE');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'SPRING FRAMEWORK');
INSERT INTO SKILL (SKILL_ID, SKILL_NAME) VALUES (SQ_SKILL_ID.NEXTVAL, 'REACT');

-- ORACLE로 들어간 5번 스킬명을 C#으로 변경
UPDATE SKILL
SET SKILL_NAME = 'C#'
WHERE SKILL_ID = 5;

-- 3. EVALUATION_ITEM 삽입
INSERT INTO EVALUATION_ITEM (ITEM_CODE, ITEM_NAME) VALUES (SQ_EVAL_ITEM_ID.NEXTVAL, '업무 수행 평가');
INSERT INTO EVALUATION_ITEM (ITEM_CODE, ITEM_NAME) VALUES (SQ_EVAL_ITEM_ID.NEXTVAL, '커뮤니케이션 능력 평가');

-- 4. CLIENT_EVAL_ITEM 삽입
INSERT INTO CLIENT_EVAL_ITEM (CLIENT_ITEM_CODE, ITEM_NAME) VALUES (SQ_CLIENT_EVAL_ITEM_ID.NEXTVAL, '협업 태도');
INSERT INTO CLIENT_EVAL_ITEM (CLIENT_ITEM_CODE, ITEM_NAME) VALUES (SQ_CLIENT_EVAL_ITEM_ID.NEXTVAL, '거래 횟수');
INSERT INTO CLIENT_EVAL_ITEM (CLIENT_ITEM_CODE, ITEM_NAME) VALUES (SQ_CLIENT_EVAL_ITEM_ID.NEXTVAL, '신용 등급');


-- 5. CLIENT 삽입
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, ADDRESS, PHONE) VALUES (SQ_CLIENT_ID.NEXTVAL, '미래IT', '서울시 강남구', '0211112222');
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, ADDRESS, PHONE) VALUES (SQ_CLIENT_ID.NEXTVAL, '코리아은행', '서울시 중구', '0233334444');
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, ADDRESS, PHONE) VALUES (SQ_CLIENT_ID.NEXTVAL, '글로벌전자', '경기 수원시', '03155556666');
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, ADDRESS, PHONE) VALUES (SQ_CLIENT_ID.NEXTVAL, '스타트업A', '서울시 마포구', '0277778888');


COMMIT;

