-- *******************************************
-- 1. 직원 및 개발자 데이터 (100명)
-- *******************************************
-- 총 100명: 개발자 70명 (ID: 10001~10070), 기타 30명 (ID: 10071~10100)
-- 직원 ID는 SQ_EMPLOYEE_ID 시퀀스를 사용 (10001부터 시작)

-- 개발자 (DEV, 70명)
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, RRN, EDUCATION, YEARS, JOB_TYPE)
SELECT 
    SQ_EMPLOYEE_ID.NEXTVAL, 
    '개발자' || LPAD(LEVEL, 2, '0'), 
    '900101' || LPAD(LEVEL, 6, '0'),
    CASE WHEN MOD(LEVEL, 3) = 0 THEN 'OO대학교 졸업' ELSE 'OO고등학교 졸업' END,
    MOD(LEVEL, 10) + 1, -- 경력 1~10년
    'DEV'
FROM DUAL CONNECT BY LEVEL <= 70;

-- 기타 직군 (30명: MARKETING 10명, RND 10명, MGMT 10명)
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, RRN, EDUCATION, YEARS, JOB_TYPE)
SELECT 
    SQ_EMPLOYEE_ID.NEXTVAL, 
    '직원' || LPAD(LEVEL+70, 2, '0'), 
    '950505' || LPAD(LEVEL+70, 6, '0'),
    'OO대학교 졸업',
    MOD(LEVEL, 5) + 2, -- 경력 2~6년
    CASE 
        WHEN LEVEL <= 10 THEN 'MARKETING'
        WHEN LEVEL <= 20 THEN 'RND'
        ELSE 'MGMT' 
    END
FROM DUAL CONNECT BY LEVEL <= 30;

-- 개발자 (DEVELOPER) 테이블 적재
INSERT INTO DEVELOPER (EMPLOYEE_ID, SKILL_LEVEL, PROJECT_ASSIGNMENT_YN)
SELECT 
    EMPLOYEE_ID,
    CASE 
        WHEN YEARS >= 7 THEN '상급'
        WHEN YEARS >= 3 THEN '중급'
        ELSE '초급'
    END,
    0 -- 초기에는 모두 미투입(가용인력)으로 설정
FROM EMPLOYEE
WHERE JOB_TYPE = 'DEV';


-- *******************************************
-- 2. 계정 (ACCOUNT)
-- *******************************************
INSERT INTO ACCOUNT (LOGIN_ID, PASSWORD_HASH, EMPLOYEE_ID, CREATED_AT)
SELECT
    'user' || EMPLOYEE_ID, 
    'hashed_password_' || EMPLOYEE_ID, 
    EMPLOYEE_ID,
    SYSDATE - (DBMS_RANDOM.VALUE * 365)
FROM EMPLOYEE;


-- *******************************************
-- 3. 경험기술 (EMPLOYEE_SKILL)
-- *******************************************
-- 개발자 70명에게 1~3개의 무작위 기술(SKILL_ID: 1~6)을 부여
-- *******************************************

-- 4. 프로젝트 (PROJECT) 
-- *******************************************
-- ID: 1, 2, 3, 4, 5 생성
-- 프로젝트 1 (종료, 발주처 1)
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_ID)
VALUES (SQ_PROJECT_ID.NEXTVAL, '미래IT 차세대 시스템 구축', DATE '2025-01-01', DATE '2025-10-31', 1);

-- 프로젝트 2 (종료 예정, 발주처 2)
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_ID)
VALUES (SQ_PROJECT_ID.NEXTVAL, '코리아은행 모바일 앱 개발', DATE '2025-05-15', DATE '2025-11-30', 2);

-- 프로젝트 3 (진행 중, 발주처 3)
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_ID)
VALUES (SQ_PROJECT_ID.NEXTVAL, '글로벌전자 AI 플랫폼 개발', DATE '2024-11-01', NULL, 3);

-- 프로젝트 4 (종료 예정, 발주처 4)
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_ID)
VALUES (SQ_PROJECT_ID.NEXTVAL, '스타트업A 초기 웹 서비스 개발', DATE '2025-09-01', DATE '2025-12-31', 4);

-- 프로젝트 5 (진행 중, 발주처 1)
INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_ID)
VALUES (SQ_PROJECT_ID.NEXTVAL, '미래IT 클라우드 전환', DATE '2025-08-01', NULL, 1);


-- *******************************************
-- 5. 투입 프로젝트 (PROJECT_ASSIGNMENT) 및 개발자 투입 여부 갱신
-- *******************************************

-- 2. (ORA-12838 해결) 
--    세션의 병렬 DML 기능을 비활성화합니다.
ALTER SESSION DISABLE PARALLEL DML;

-- 3. (목표 쿼리) 
--    '진행 중'인 프로젝트(3번, 5번)에 투입된 개발자의 상태를 1로 갱신합니다.


-- *******************************************
-- 5-2. 개발자 투입 여부 갱신 (PROJECT_ASSIGNMENT_YN)
-- (이것은 UPDATE 문이라서 SELECT가 들어갈 수밖에 없습니다)
-- *******************************************
-- 진행 중인 프로젝트 (END_DATE IS NULL)에 투입된 개발자의 PROJECT_ASSIGNMENT_YN을 1로 갱신
COMMIT;
ALTER SESSION DISABLE PARALLEL DML;
UPDATE DEVELOPER D
SET PROJECT_ASSIGNMENT_YN = 1
WHERE EXISTS (
    SELECT 1 
    FROM PROJECT_ASSIGNMENT PA
    JOIN PROJECT P ON PA.PROJECT_ID = P.PROJECT_ID
    WHERE PA.EMPLOYEE_ID = D.EMPLOYEE_ID
      AND P.END_DATE IS NULL
);


-- *******************************************
-- 6. 평가 (EVALUATION) 및 평가 상세 테이블
-- *******************************************
-- 프로젝트 1 (종료)에 대한 평가 생성 (피평가자: P1 투입 직원 10명)
INSERT INTO EVALUATION (EVALUATION_ID, PROJECT_ID, EVALUATEE_EMPLOYEE_ID, EVAL_DATE)
SELECT SQ_EVALUATION_ID.NEXTVAL, 1, EMPLOYEE_ID, DATE '2025-11-05' 
FROM PROJECT_ASSIGNMENT PA
WHERE PA.PROJECT_ID = 1;

-- 프로젝트 1의 투입 PM (10001)을 평가자로 지정하고 PM평가 생성
INSERT INTO EVAL_PM (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10001 -- PM ID
FROM EVALUATION E
WHERE E.PROJECT_ID = 1 AND E.EVALUATEE_EMPLOYEE_ID != 10001;

-- 프로젝트 1의 고객 (CLIENT_ID=1)을 평가자로 지정하고 고객평가 생성
INSERT INTO EVAL_CUSTOMER (EVALUATION_ID, EVALUATOR_CLIENT_ID)
SELECT E.EVALUATION_ID, 1 -- 고객 ID
FROM EVALUATION E
WHERE E.PROJECT_ID = 1;

-- 프로젝트 1의 동료 (10002)를 평가자로 지정하고 동료평가 생성
INSERT INTO EVAL_PEER (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10002 -- 동료 ID
FROM EVALUATION E
WHERE E.PROJECT_ID = 1 AND E.EVALUATEE_EMPLOYEE_ID != 10002;

-- *******************************************
-- 6. 평가 (EVALUATION) 및 평가 상세 테이블
-- *******************************************

-- [6-1] 프로젝트 1 (종료) 평가 생성 (10명)
INSERT INTO EVALUATION (EVALUATION_ID, PROJECT_ID, EVALUATEE_EMPLOYEE_ID, EVAL_DATE)
SELECT SQ_EVALUATION_ID.NEXTVAL, 1, EMPLOYEE_ID, DATE '2025-11-05' 
FROM PROJECT_ASSIGNMENT PA
WHERE PA.PROJECT_ID = 1;

-- P1: PM평가 (PM: 10001)
INSERT INTO EVAL_PM (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10001 
FROM EVALUATION E
WHERE E.PROJECT_ID = 1 AND E.EVALUATEE_EMPLOYEE_ID != 10001;

-- P1: 고객평가 (Client: 1)
INSERT INTO EVAL_CUSTOMER (EVALUATION_ID, EVALUATOR_CLIENT_ID)
SELECT E.EVALUATION_ID, 1 
FROM EVALUATION E
WHERE E.PROJECT_ID = 1;

-- P1: 동료평가 (Peer: 10002)
INSERT INTO EVAL_PEER (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10002 
FROM EVALUATION E
WHERE E.PROJECT_ID = 1 AND E.EVALUATEE_EMPLOYEE_ID != 10002;


-- [6-2] 프로젝트 2 (종료 예정) 평가 생성 (5명)
INSERT INTO EVALUATION (EVALUATION_ID, PROJECT_ID, EVALUATEE_EMPLOYEE_ID, EVAL_DATE)
SELECT SQ_EVALUATION_ID.NEXTVAL, 2, EMPLOYEE_ID, DATE '2025-12-05' -- P2 종료일(11/30) 이후
FROM PROJECT_ASSIGNMENT PA
WHERE PA.PROJECT_ID = 2;

-- P2: PM평가 (PM: 10011)
INSERT INTO EVAL_PM (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10011
FROM EVALUATION E
WHERE E.PROJECT_ID = 2 AND E.EVALUATEE_EMPLOYEE_ID != 10011;

-- P2: 고객평가 (Client: 2)
INSERT INTO EVAL_CUSTOMER (EVALUATION_ID, EVALUATOR_CLIENT_ID)
SELECT E.EVALUATION_ID, 2 
FROM EVALUATION E
WHERE E.PROJECT_ID = 2;

-- P2: 동료평가 (Peer: 10012)
INSERT INTO EVAL_PEER (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10012
FROM EVALUATION E
WHERE E.PROJECT_ID = 2 AND E.EVALUATEE_EMPLOYEE_ID != 10012;


-- [6-3] 프로젝트 4 (종료 예정) 평가 생성 (5명)
INSERT INTO EVALUATION (EVALUATION_ID, PROJECT_ID, EVALUATEE_EMPLOYEE_ID, EVAL_DATE)
SELECT SQ_EVALUATION_ID.NEXTVAL, 4, EMPLOYEE_ID, DATE '2026-01-05' -- P4 종료일(12/31) 이후
FROM PROJECT_ASSIGNMENT PA
WHERE PA.PROJECT_ID = 4;

-- P4: PM평가 (PM: 10016)
INSERT INTO EVAL_PM (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10016
FROM EVALUATION E
WHERE E.PROJECT_ID = 4 AND E.EVALUATEE_EMPLOYEE_ID != 10016;

-- P4: 고객평가 (Client: 4)
INSERT INTO EVAL_CUSTOMER (EVALUATION_ID, EVALUATOR_CLIENT_ID)
SELECT E.EVALUATION_ID, 4 
FROM EVALUATION E
WHERE E.PROJECT_ID = 4;

-- P4: 동료평가 (Peer: 10017)
INSERT INTO EVAL_PEER (EVALUATION_ID, EVALUATOR_EMPLOYEE_ID)
SELECT E.EVALUATION_ID, 10017
FROM EVALUATION E
WHERE E.PROJECT_ID = 4 AND E.EVALUATEE_EMPLOYEE_ID != 10017;


-- [6-4] 평가결과 (EVALUATION_SCORE) 적재 (P1, P2, P4)
-- (P1: 10명, P2: 5명, P4: 5명 -> 총 20명의 평가 점수 생성)
INSERT INTO EVALUATION_SCORE (EVALUATION_ID, ITEM_CODE, SCORE, EVALUATION_COMMENT)
SELECT 
    E.EVALUATION_ID, 
    EI.ITEM_CODE, 
    DBMS_RANDOM.VALUE(70, 99),
    CASE 
        WHEN EI.ITEM_CODE = 1 THEN '업무 수행 능력이 우수함.'
        WHEN EI.ITEM_CODE = 2 THEN '팀원과의 협업 및 소통 능력이 뛰어남.'
        ELSE '기타 의견'
    END
FROM EVALUATION E, EVALUATION_ITEM EI
WHERE E.PROJECT_ID IN (1, 2, 4); -- 1, 2, 4번 프로젝트의 평가에 대해 점수 생성


-- 평가결과 (EVALUATION_SCORE) 적재
INSERT INTO EVALUATION_SCORE (EVALUATION_ID, ITEM_CODE, SCORE, EVALUATION_COMMENT)
SELECT 
    E.EVALUATION_ID, 
    EI.ITEM_CODE, 
    DBMS_RANDOM.VALUE(70, 99),
    CASE EI.ITEM_CODE
        WHEN 1 THEN '업무 수행 능력이 우수함.'
        WHEN 2 THEN '팀원과의 협업 및 소통 능력이 뛰어남.'
    END
FROM EVALUATION E, EVALUATION_ITEM EI
WHERE E.PROJECT_ID = 1;

-- *******************************************
-- 7. 고객신용평가 (CLIENT_EVALUATION) 및 결과
-- *******************************************
-- 프로젝트 1 참여 직원(10001)이 고객(1:미래IT)을 평가

INSERT INTO CLIENT_EVALUATION (CLIENT_EVALUATION_ID, CLIENT_ID, EVALUATOR_EMPLOYEE_ID, EVAL_DATE) 
VALUES (SQ_CLIENT_EVALUATION_ID.NEXTVAL, 1, 10001, DATE '2025-11-10');

-- 프로젝트 4 참여 직원(10041)이 고객(4:스타트업A)을 평가
INSERT INTO CLIENT_EVALUATION (CLIENT_EVALUATION_ID, CLIENT_ID, EVALUATOR_EMPLOYEE_ID, EVAL_DATE) 
VALUES (SQ_CLIENT_EVALUATION_ID.NEXTVAL, 4, 10041, DATE '2026-01-05');

-- 고객신용평가결과 (CLIENT_EVALUATION_SCORE) 적재
INSERT INTO CLIENT_EVALUATION_SCORE (CLIENT_EVALUATION_ID, CLIENT_ITEM_CODE, SCORE)
SELECT
    CE.CLIENT_EVALUATION_ID,
    CEI.CLIENT_ITEM_CODE,
    DBMS_RANDOM.VALUE(50, 100)
FROM CLIENT_EVALUATION CE, CLIENT_EVAL_ITEM CEI;

COMMIT;