-- 기술 
CREATE TABLE SKILL (
    SKILL_ID NUMBER(2) NOT NULL, -- 기술을 고유하게 식별하는 ID (PK)
    SKILL_NAME VARCHAR2(100) NOT NULL, -- 기술의 이름
    CONSTRAINT PK_SKILL PRIMARY KEY (SKILL_ID)
);

-- 평가항목
CREATE TABLE EVALUATION_ITEM (
    ITEM_CODE NUMBER(1) NOT NULL, -- 평가 항목을 고유하게 식별하는 ID (PK)
    ITEM_NAME VARCHAR2(100) NOT NULL, -- 평가 항목의 이름
    CONSTRAINT PK_EVAL_ITEM PRIMARY KEY (ITEM_CODE)
);

-- 고객신용평가항목
CREATE TABLE CLIENT_EVAL_ITEM (
    CLIENT_ITEM_CODE NUMBER(1) NOT NULL, -- 평가 항목을 고유하게 식별하는 ID (PK)
    ITEM_NAME VARCHAR2(100) NOT NULL, -- 평가 항목의 이름
    CONSTRAINT PK_CLIENT_EVAL_ITEM PRIMARY KEY (CLIENT_ITEM_CODE)
);

-- 직무
CREATE TABLE ROLE_T (
    ROLE_ID NUMBER(2) NOT NULL, -- 직무를 고유하게 식별하는 ID (PK)
    ROLE_NAME VARCHAR2(100) NOT NULL, -- 직무의 이름
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID)
);

-- 고객(발주처)
CREATE TABLE CLIENT (
    CLIENT_ID NUMBER(4) NOT NULL, -- 회사를 고유하게 식별하는 ID (PK)
    CLIENT_NAME VARCHAR2(150), -- 회사의 이름
    ADDRESS VARCHAR2(200), -- 회사의 주소
    PHONE VARCHAR2(11), -- 회사의 전화번호
    CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID)
);

-- 직원
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(5) NOT NULL, -- 직원을 고유하게 식별하는 ID (PK)
    EMPLOYEE_NAME VARCHAR2(100), -- 직원의 이름
    RRN VARCHAR2(13), -- 직원의 주민등록번호
    EDUCATION VARCHAR2(100), -- 직원의 최종학력
    YEARS NUMBER(2), -- 직원의 경력
    JOB_TYPE VARCHAR2(20) NOT NULL, -- 직원이 속한 직군을 구분하기 위한 코드값
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UK_EMPLOYEE_RRN UNIQUE (RRN) -- 주민등록번호는 UNIQUE
);

-- 개발자
CREATE TABLE DEVELOPER (
    EMPLOYEE_ID NUMBER(5) NOT NULL, 
    SKILL_LEVEL VARCHAR2(10), -- 직원의 기술 등급
    PROJECT_ASSIGNMENT_YN NUMBER(1) NOT NULL, -- 현재 프로젝트 투입 여부
    CONSTRAINT PK_DEVELOPER PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_DEVELOPER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

-- 계정
CREATE TABLE ACCOUNT (
    LOGIN_ID VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (LOGIN_ID),
    CONSTRAINT FK_ACCOUNT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT UK_ACCOUNT_EMPLOYEE_ID UNIQUE (EMPLOYEE_ID)
);


-- 경험 기술
CREATE TABLE EMPLOYEE_SKILL (
    EMPLOYEE_ID NUMBER(5) NOT NULL, -- 직원의 ID (PK, FK)
    SKILL_ID NUMBER(2) NOT NULL, -- 기술의 ID (PK, FK)
    CONSTRAINT PK_EMPLOYEE_SKILL PRIMARY KEY (EMPLOYEE_ID, SKILL_ID),
    CONSTRAINT FK_ESKILL_DEVELOPER FOREIGN KEY (EMPLOYEE_ID) REFERENCES DEVELOPER (EMPLOYEE_ID),
    CONSTRAINT FK_ESKILL_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID)
);

-- 프로젝트
CREATE TABLE PROJECT (
    PROJECT_ID NUMBER(5) NOT NULL, -- 프로젝트를 고유하게 식별하는 ID (PK)
    PROJECT_NAME VARCHAR2(200), -- 프로젝트의 이름 또는 제목
    START_DATE DATE, -- 프로젝트가 실제로 시작된 날짜
    END_DATE DATE, -- 프로젝트가 종료된 날짜 (진행 중인 경우 NULL)
    CLIENT_ID NUMBER(4) NOT NULL, -- 발주처/요청한 고객사 ID (FK)
    CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID),
    CONSTRAINT FK_PROJECT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID)
);

-- 투입 프로젝트
CREATE TABLE PROJECT_ASSIGNMENT (
    ASSIGNMENT_ID NUMBER(6) NOT NULL, -- 투입(배정) 기록을 고유하게 식별하는 ID (PK)
    PROJECT_ID NUMBER(5) NOT NULL, -- 투입이 속한 프로젝트의 ID (FK)
    EMPLOYEE_ID NUMBER(5) NOT NULL, -- 해당 프로젝트에 투입된 직원의 ID (FK)
    ROLE_ID NUMBER(2), -- 직원이 해당 프로젝트에서 맡은 직무 ID (FK)
    ASSIGN_START DATE, -- 직원이 프로젝트 업무를 시작한 날짜
    ASSIGN_END DATE, -- 직원이 해당 프로젝트 업무에서 빠지는 날짜
    CONSTRAINT PK_PROJECT_ASSIGNMENT PRIMARY KEY (ASSIGNMENT_ID),
    CONSTRAINT FK_PA_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    CONSTRAINT FK_PA_DEVELOPER FOREIGN KEY (EMPLOYEE_ID) REFERENCES DEVELOPER (EMPLOYEE_ID),
    CONSTRAINT FK_PA_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE_T (ROLE_ID)
);

-- 평가
CREATE TABLE EVALUATION (
    EVALUATION_ID NUMBER(6) NOT NULL,
    PROJECT_ID NUMBER(5) NOT NULL,
    EVALUATEE_EMPLOYEE_ID NUMBER(5) NOT NULL,
    EVAL_DATE DATE DEFAULT SYSDATE NOT NULL,  -- 평가 완료 날짜
    CONSTRAINT PK_EVALUATION PRIMARY KEY (EVALUATION_ID),
    CONSTRAINT FK_EVAL_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    CONSTRAINT FK_EVAL_DEVELOPER FOREIGN KEY (EVALUATEE_EMPLOYEE_ID) REFERENCES DEVELOPER(EMPLOYEE_ID)
);


-- 고객평가
CREATE TABLE EVAL_CUSTOMER (
    EVALUATION_ID NUMBER(6) NOT NULL, -- 평가의 PK를 공유 (PK, FK)
    EVALUATOR_CLIENT_ID NUMBER(5) NOT NULL, -- 평가를 수행한 고객 (FK)
    CONSTRAINT PK_EVAL_CUSTOMER PRIMARY KEY (EVALUATION_ID),
    CONSTRAINT FK_ECUST_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION (EVALUATION_ID),
    CONSTRAINT FK_ECUST_CLIENT FOREIGN KEY (EVALUATOR_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID)
);

-- PM평가
CREATE TABLE EVAL_PM (
    EVALUATION_ID NUMBER(6) NOT NULL, -- 평가의 PK를 공유 (PK, FK)
    EVALUATOR_EMPLOYEE_ID NUMBER(5) NOT NULL, -- 평가를 수행한 PM (FK)
    CONSTRAINT PK_EVAL_PM PRIMARY KEY (EVALUATION_ID),
    CONSTRAINT FK_EPM_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION (EVALUATION_ID),
    CONSTRAINT FK_EPM_DEVELOPER FOREIGN KEY (EVALUATOR_EMPLOYEE_ID) REFERENCES DEVELOPER (EMPLOYEE_ID)
);

-- 동료평가
CREATE TABLE EVAL_PEER (
    EVALUATION_ID NUMBER(6) NOT NULL, -- 평가의 PK를 공유 (PK, FK)
    EVALUATOR_EMPLOYEE_ID NUMBER(5) NOT NULL, -- 평가를 수행한 동료 (FK)
    CONSTRAINT PK_EVAL_PEER PRIMARY KEY (EVALUATION_ID),
    CONSTRAINT FK_EPEER_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION (EVALUATION_ID),
    CONSTRAINT FK_EPEER_DEVELOPER FOREIGN KEY (EVALUATOR_EMPLOYEE_ID) REFERENCES DEVELOPER (EMPLOYEE_ID)
);

-- 평가결과
CREATE TABLE EVALUATION_SCORE (
    EVALUATION_ID NUMBER(6) NOT NULL, -- 평가 내역을 고유하게 식별하는 ID (PK, FK)
    ITEM_CODE NUMBER(1) NOT NULL, -- 평가 항목을 고유하게 식별하는 ID (PK, FK)
    SCORE NUMBER(3) NOT NULL, -- 해당 항목에 대한 점수
    EVALUATION_COMMENT VARCHAR2(255) NOT NULL, -- 해당 항목에 대한 서술형 평가 내용
    CONSTRAINT PK_EVAL_SCORE PRIMARY KEY (EVALUATION_ID, ITEM_CODE),
    CONSTRAINT FK_ESCORE_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION (EVALUATION_ID),
    CONSTRAINT FK_ESCORE_EVAL_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES EVALUATION_ITEM (ITEM_CODE)
);

-- 고객신용평가
CREATE TABLE CLIENT_EVALUATION (
    CLIENT_EVALUATION_ID NUMBER(5) NOT NULL,        -- PK
    CLIENT_ID NUMBER(4) NOT NULL,                  -- FK: CLIENT
    EVALUATOR_EMPLOYEE_ID NUMBER(5) NOT NULL,      -- FK: DEVELOPER
    EVAL_DATE DATE DEFAULT SYSDATE NOT NULL,       -- 평가 완료 날짜
    CONSTRAINT PK_CLIENT_EVALUATION PRIMARY KEY (CLIENT_EVALUATION_ID),
    CONSTRAINT FK_CEVAL_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
    CONSTRAINT FK_CEVAL_DEVELOPER FOREIGN KEY (EVALUATOR_EMPLOYEE_ID) REFERENCES DEVELOPER(EMPLOYEE_ID)
);


-- 고객신용평가결과
CREATE TABLE CLIENT_EVALUATION_SCORE (
    CLIENT_EVALUATION_ID NUMBER(5) NOT NULL,  -- PK, FK
    CLIENT_ITEM_CODE NUMBER(1) NOT NULL,      -- PK, FK
    SCORE NUMBER(3) NOT NULL,                 -- 평가 점수
    CONSTRAINT PK_CLIENT_EVAL_SCORE PRIMARY KEY (CLIENT_EVALUATION_ID, CLIENT_ITEM_CODE),
    CONSTRAINT FK_CESCORE_CEVAL FOREIGN KEY (CLIENT_EVALUATION_ID) REFERENCES CLIENT_EVALUATION(CLIENT_EVALUATION_ID),
    CONSTRAINT FK_CESCORE_CEVAL_ITEM FOREIGN KEY (CLIENT_ITEM_CODE) REFERENCES CLIENT_EVAL_ITEM(CLIENT_ITEM_CODE)
);


-- 1. (초기화) 기존 테이블 및 시퀀스 삭제 (오류 무시)
-- (순서와 상관없이 삭제할 수 있도록 CASCADE CONSTRAINTS 사용)
-- BEGIN
--     FOR t IN (SELECT table_name FROM user_tables) LOOP
--         EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS';
--     END LOOP;

--     FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
--         EXECUTE IMMEDIATE 'DROP SEQUENCE "' || s.sequence_name || '"';
--     END LOOP;
-- END;
-- /
