-- 기술(SKILL) 테이블의 기술ID를 위한 시퀀스
CREATE SEQUENCE SQ_SKILL_ID START WITH 1 INCREMENT BY 1;

-- 평가(EVALUATION) 테이블의 평가ID를 위한 시퀀스
CREATE SEQUENCE SQ_EVALUATION_ID START WITH 1 INCREMENT BY 1;

-- 평가항목(EVALUATION_ITEM) 테이블의 평가항목ID를 위한 시퀀스
CREATE SEQUENCE SQ_EVAL_ITEM_ID START WITH 1 INCREMENT BY 1;

-- 프로젝트(PROJECT) 테이블의 프로젝트ID를 위한 시퀀스
CREATE SEQUENCE SQ_PROJECT_ID START WITH 1 INCREMENT BY 1;

-- 직무(ROLE) 테이블의 직무ID를 위한 시퀀스
CREATE SEQUENCE SQ_ROLE_ID START WITH 1 INCREMENT BY 1;

-- 투입 프로젝트(PROJECT_ASSIGNMENT) 테이블의 투입ID를 위한 시퀀스
CREATE SEQUENCE SQ_ASSIGNMENT_ID START WITH 1 INCREMENT BY 1;

-- 고객(CLIENT) 테이블의 고객ID를 위한 시퀀스
CREATE SEQUENCE SQ_CLIENT_ID START WITH 1 INCREMENT BY 1;

-- 고객신용평가(CLIENT_EVALUATION) 테이블의 고객신용평가ID를 위한 시퀀스
CREATE SEQUENCE SQ_CLIENT_EVALUATION_ID START WITH 1 INCREMENT BY 1;

-- 고객신용평가항목(CLIENT_EVAL_ITEM) 테이블의 고객신용평가항목ID를 위한 시퀀스
CREATE SEQUENCE SQ_CLIENT_EVAL_ITEM_ID START WITH 1 INCREMENT BY 1;

-- 직원ID는 10001부터 시작하도록 별도 시퀀스 정의 (10000~49999 범위 반영)
CREATE SEQUENCE SQ_EMPLOYEE_ID START WITH 10001 INCREMENT BY 1;


