-- CLIENT (고객) 시퀀스
CREATE SEQUENCE CLIENT_SEQ
    START WITH 1      -- 시퀀스가 1부터 시작
    INCREMENT BY 1    -- 1씩 증가
    NOCACHE
    NOCYCLE;

-- CLIENT (고객) Table
CREATE TABLE CLIENT (
    CLIENT_ID NUMBER(4) PRIMARY KEY, -- 고객ID
    CLIENT_NAME VARCHAR2(150), -- 고객명
    ADDRESS VARCHAR2(200), -- 주소
    PHONE VARCHAR2(11) -- 전화번호
);


-- CLIENT_ITEM_CODE 시퀀스
CREATE SEQUENCE CLIENT_ITEM_SEQ
    START WITH 1      -- 시퀀스가 1부터 시작
    INCREMENT BY 1    -- 1씩 증가
    NOCACHE
    NOCYCLE;

-- CLIENT_EVAL_ITEM (고객신용평가항목) Table
CREATE TABLE CLIENT_EVAL_ITEM (
    CLIENT_ITEM_CODE NUMBER(1) PRIMARY KEY, -- 고객신용평가항목ID
    ITEM_NAME VARCHAR2(100) NOT NULL -- 고객신용평가항목명
);

-- CLIENT_EVALUATION (고객신용평가) Table
CREATE TABLE CLIENT_EVALUATION_EVENT (
    CLIENT_EVALUATION_ID NUMBER(6) PRIMARY KEY, -- 고객신용평가ID
    CLIENT_ID NUMBER(4) NOT NULL, -- 고객ID
    EVALUATOR_EMPLOYEE_ID NUMBER(5) NOT NULL, -- 평가자직원ID
    EVAL_DATE DATE DEFAULT SYSDATE NOT NULL, -- 평가일
    CONSTRAINT FK_CLEVAL_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
    CONSTRAINT FK_CLEVAL_EMPLOYEE FOREIGN KEY (EVALUATOR_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- CLIENT_EVALUATION_SCORE (고객신용평가결과) Table
CREATE TABLE CLIENT_EVALUATION_SCORE (
    CLIENT_EVALUATION_ID NUMBER(6) NOT NULL, -- 고객신용평가ID
    CLIENT_ITEM_CODE NUMBER(1) NOT NULL, -- 고객신용평가항목ID
    SCORE NUMBER(3) NOT NULL CHECK (SCORE BETWEEN 0 AND 100), -- 평점
    PRIMARY KEY (CLIENT_EVALUATION_ID, CLIENT_ITEM_CODE),
    CONSTRAINT FK_CLEVALSCORE_EVENT FOREIGN KEY (CLIENT_EVALUATION_ID) REFERENCES CLIENT_EVALUATION_EVENT(CLIENT_EVALUATION_ID),
    CONSTRAINT FK_CLEVALSCORE_ITEM FOREIGN KEY (CLIENT_ITEM_CODE) REFERENCES CLIENT_EVAL_ITEM(CLIENT_ITEM_CODE)
);