-- 직원
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID       INT             NOT NULL,
    EMPLOYEE_NAME     VARCHAR2(100)   NOT NULL,
    RRN               VARCHAR2(20)    NOT NULL UNIQUE,
    EDUCATION         VARCHAR2(100),
    YEARS             SMALLINT,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

-- 경영관리
CREATE TABLE MANAGEMENT (
    EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT PK_MANAGEMENT PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_MANAGEMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);

-- 연구개발
CREATE TABLE RND (
    EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT PK_RND PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_RND_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);

-- 마케팅
CREATE TABLE MARKETING (
    EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT PK_MARKETING PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_MARKETING_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);

-- 개발자
CREATE TABLE DEVELOPER (
    EMPLOYEE_ID     INT           NOT NULL,
    SKILL_LEVEL     VARCHAR2(10),
    PROJECT_ACTIVE  NUMBER(1)     NOT NULL,  -- 1(투입), 0(미투입)
    CONSTRAINT PK_DEVELOPER PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_DEVELOPER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);
