-- 직원
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID       NUMBER(5)       NOT NULL,
    EMPLOYEE_NAME     VARCHAR2(100)   NOT NULL,
    RRN               VARCHAR2(13)    NOT NULL UNIQUE,
    EDUCATION         VARCHAR2(100),
    YEARS             NUMBER(2),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

-- 경영관리
CREATE TABLE MANAGEMENT (
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    CONSTRAINT PK_MANAGEMENT PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_MANAGEMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);

-- 연구개발
CREATE TABLE RND (
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    CONSTRAINT PK_RND PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_RND_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);

-- 마케팅
CREATE TABLE MARKETING (
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    CONSTRAINT PK_MARKETING PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_MARKETING_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);

-- 개발자
CREATE TABLE DEVELOPER (
    EMPLOYEE_ID     NUMBER(5) NOT NULL,
    SKILL_LEVEL     VARCHAR2(10),
    PROJECT_ACTIVE  NUMBER(1)     NOT NULL,  -- 1(투입), 0(미투입)
    CONSTRAINT PK_DEVELOPER PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_DEVELOPER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON DELETE CASCADE
);



-- ACCOUNT (계정) Table
CREATE TABLE ACCOUNT (
    LOGIN_ID VARCHAR2(100) PRIMARY KEY, -- 로그인ID
    PASSWORD_HASH VARCHAR2(255) NOT NULL, -- 비밀번호
    EMPLOYEE_ID NUMBER(5) NOT NULL UNIQUE, -- 직원ID
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, -- 가입일
    CONSTRAINT FK_ACCOUNT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- ROLE_ID 시퀀스 
CREATE SEQUENCE ROLE_SEQ
    START WITH 1      -- 시퀀스가 1부터 시작
    INCREMENT BY 1    -- 1씩 증가
    NOCACHE           -- 캐시를 사용하지 않음
    NOCYCLE;          -- 시퀀스가 한도에 도달해도 다시 시작하지 않음

-- ROLE (직무) Table
CREATE TABLE ROLE (
    ROLE_ID NUMBER(2) PRIMARY KEY, -- 직무ID
    ROLE_NAME VARCHAR2(100) NOT NULL -- 직무명
);

-- 직무ID 삽입시 예시
-- INSERT INTO ROLE (ROLE_ID, ROLE_NAME)
-- VALUES (ROLE_SEQ.NEXTVAL, '데이터 분석가');