-- ITEM_CODE 시퀀스
CREATE SEQUENCE EVAL_ITEM_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- EVALUATION_ITEM (평가항목) Table
CREATE TABLE EVALUATION_ITEM (
    ITEM_CODE NUMBER(1) PRIMARY KEY, -- 평가항목ID
    ITEM_NAME VARCHAR2(100) NOT NULL -- 평가항목명
);

-- EVALUATION_ID 시퀀스 
CREATE SEQUENCE EVAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- EVALUATION (평가) Table (Super Table)
CREATE TABLE EVALUATION (
    EVALUATION_ID NUMBER(6) PRIMARY KEY, -- 평가ID
    PROJECT_ID NUMBER(5) NOT NULL, -- 프로젝트ID
    EVALUATEE_EMPLOYEE_ID NUMBER(5) NOT NULL, -- 피평가자ID
    EVAL_DATE DATE DEFAULT SYSDATE NOT NULL, -- 평가일
    CONSTRAINT FK_EVAL_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    CONSTRAINT FK_EVAL_EVALUATEE FOREIGN KEY (EVALUATEE_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- CLIENT_EVALUATION (고객평가) Table (SUB Table)
CREATE TABLE CLIENT_EVALUATION (
    EVALUATION_ID NUMBER(6) PRIMARY KEY, -- 평가ID
    EVALUATOR_CLIENT_ID NUMBER(4) NOT NULL, -- 평가자고객ID
    CONSTRAINT FK_CLIENTEVAL_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION(EVALUATION_ID),
    CONSTRAINT FK_CLIENTEVAL_CLIENT FOREIGN KEY (EVALUATOR_CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

-- PM_EVALUATION (PM평가) Table (SUB Table)
CREATE TABLE PM_EVALUATION (
    EVALUATION_ID NUMBER(6) PRIMARY KEY, -- 평가ID
    EVALUATOR_EMPLOYEE_ID NUMBER(4) NOT NULL, -- 평가자직원ID
    CONSTRAINT FK_PMEVAL_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION(EVALUATION_ID),
    CONSTRAINT FK_PMEVAL_EMPLOYEE FOREIGN KEY (EVALUATOR_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- PEER_EVALUATION (동료평가) Table (SUB Table)
CREATE TABLE PEER_EVALUATION (
    EVALUATION_ID NUMBER(6) PRIMARY KEY, -- 평가ID
    EVALUATOR_EMPLOYEE_ID NUMBER(4) NOT NULL, -- 평가자직원ID
    CONSTRAINT FK_PEEREVAL_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION(EVALUATION_ID),
    CONSTRAINT FK_PEEREVAL_EMPLOYEE FOREIGN KEY (EVALUATOR_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- EVALUATION_SCORE (평가결과) Table
CREATE TABLE EVALUATION_SCORE (
    EVALUATION_ID NUMBER(6) NOT NULL, -- 평가ID
    ITEM_CODE NUMBER(1) NOT NULL, -- 평가항목ID
    SCORE NUMBER(3) NOT NULL CHECK (SCORE BETWEEN 0 AND 100), -- 평점
    EVALUATION_COMMENT VARCHAR2(255) NOT NULL, -- 평가내용
    PRIMARY KEY (EVALUATION_ID, ITEM_CODE),
    CONSTRAINT FK_EVALSCORE_EVALUATION FOREIGN KEY (EVALUATION_ID) REFERENCES EVALUATION(EVALUATION_ID),
    CONSTRAINT FK_EVALSCORE_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES EVALUATION_ITEM(ITEM_CODE)
);

