-- PROJECT (프로젝트) Table
CREATE TABLE PROJECT (
    PROJECT_ID NUMBER(5) PRIMARY KEY, -- 프로젝트ID
    PROJECT_NAME VARCHAR2(200), -- 프로젝트명
    START_DATE DATE, -- 착수일자
    END_DATE DATE, -- 종료일자
    CLIENT_ID NUMBER(4) NOT NULL, -- 발주처ID
    CONSTRAINT FK_PROJECT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

---기술 시퀀스
CREATE SEQUENCE SKILL_SEQ
    START WITH 1      -- 시퀀스가 1부터 시작
    INCREMENT BY 1    -- 1씩 증가
    NOCACHE
    NOCYCLE;


-- SKILL (기술) Table
CREATE TABLE SKILL (
    SKILL_ID NUMBER(2) PRIMARY KEY, -- 기술ID
    SKILL_NAME VARCHAR2(100) NOT NULL -- 기술명
);

-- EMPLOYEE_SKILL (경험기술) Table
CREATE TABLE EMPLOYEE_SKILL (
    EMPLOYEE_ID NUMBER(10) NOT NULL, -- 직원ID
    SKILL_ID NUMBER(10) NOT NULL, -- 기술ID
    PRIMARY KEY (EMPLOYEE_ID, SKILL_ID),
    CONSTRAINT FK_ESKILL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_ESKILL_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID)
);

-- PROJECT_ASSIGNMENT (투입 프로젝트) Table
CREATE TABLE PROJECT_ASSIGNMENT (
    ASSIGNMENT_ID NUMBER(6) PRIMARY KEY, -- 투입ID
    PROJECT_ID NUMBER(5) NOT NULL, -- 프로젝트ID
    EMPLOYEE_ID NUMBER(5) NOT NULL, -- 직원ID
    ROLE_ID NUMBER(2), -- 직무ID
    ASSIGN_START DATE, -- 투입시작일
    ASSIGN_END DATE, -- 투입종료일
    CONSTRAINT FK_ASSIGN_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    CONSTRAINT FK_ASSIGN_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_ASSIGN_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);